INFO: Default loss without VGG
INFO: No cutoff
INFO: 2023-08-21 19:41:28 Argument batch_size: 8
INFO: 2023-08-21 19:41:28 Argument code_test: True
INFO: 2023-08-21 19:41:28 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-08-21 19:41:28 Argument data_val_path: ./../data/data_96/val/data_val_chr19_96.npy
INFO: 2023-08-21 19:41:28 Argument device_number: 1
INFO: 2023-08-21 19:41:28 Argument epoch: 1
INFO: 2023-08-21 19:41:28 Argument local_rank: 0
INFO: 2023-08-21 19:41:28 Argument loss: single_channel_no_vgg
INFO: 2023-08-21 19:41:28 Argument max_HiC: 255
INFO: 2023-08-21 19:41:28 Argument num_gpu: 1
INFO: 2023-08-21 19:41:28 Argument num_workers: 1
INFO: 2023-08-21 19:41:28 Argument patch_size: 96
INFO: 2023-08-21 19:41:28 Argument resume_epoch: 0
INFO: 2023-08-21 19:41:28 Argument resume_path: None
INFO: 2023-08-21 19:41:28 Argument rgb: False
INFO: 2023-08-21 19:41:28 Argument train_dataset: hic
INFO: 2023-08-21 19:41:28 Argument val_datasets: ['hic']
INFO: 2023-08-21 19:41:32 epoch:0 dataset: 1/17 step: 0/155 time:0.60+2.00 loss_avg:2.2300e-01
INFO: 2023-08-21 19:41:33 epoch:0 dataset: 1/17 step: 1/155 time:0.00+0.87 loss_avg:1.8877e-01
INFO: Training on data_train_chr7_96.npy complete.
INFO: 2023-08-21 19:41:34 epoch:0 dataset: 2/17 step: 0/90 time:0.57+0.96 loss_avg:2.5133e-01
INFO: 2023-08-21 19:41:35 epoch:0 dataset: 2/17 step: 1/90 time:0.00+0.87 loss_avg:2.4228e-01
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 334, in <module>
    train(model, args)
  File "./train_1d.py", line 210, in train
    val_hicrep = evaluate(model, data_val_path, val_dataset, epoch, step)
  File "./train_1d.py", line 235, in evaluate
    get_predictions(val_save_path, data_val_path, 1534, dim) #assemble into one big matrix
NameError: name 'dim' is not defined

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7fb1f815ad80>
