INFO: Default loss without VGG
INFO: No cutoff
INFO: 2023-08-21 19:42:31 Argument batch_size: 8
INFO: 2023-08-21 19:42:31 Argument code_test: True
INFO: 2023-08-21 19:42:31 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-08-21 19:42:31 Argument data_val_path: ./../data/data_96/val/data_val_chr19_96.npy
INFO: 2023-08-21 19:42:31 Argument device_number: 1
INFO: 2023-08-21 19:42:31 Argument epoch: 1
INFO: 2023-08-21 19:42:31 Argument local_rank: 0
INFO: 2023-08-21 19:42:31 Argument loss: single_channel_no_vgg
INFO: 2023-08-21 19:42:31 Argument max_HiC: 255
INFO: 2023-08-21 19:42:31 Argument num_gpu: 1
INFO: 2023-08-21 19:42:31 Argument num_workers: 1
INFO: 2023-08-21 19:42:31 Argument patch_size: 96
INFO: 2023-08-21 19:42:31 Argument resume_epoch: 0
INFO: 2023-08-21 19:42:31 Argument resume_path: None
INFO: 2023-08-21 19:42:31 Argument rgb: False
INFO: 2023-08-21 19:42:31 Argument train_dataset: hic
INFO: 2023-08-21 19:42:31 Argument val_datasets: ['hic']
INFO: 2023-08-21 19:42:35 epoch:0 dataset: 1/17 step: 0/155 time:0.60+2.14 loss_avg:2.2300e-01
INFO: 2023-08-21 19:42:36 epoch:0 dataset: 1/17 step: 1/155 time:0.00+0.90 loss_avg:1.8877e-01
INFO: Training on data_train_chr7_96.npy complete.
INFO: 2023-08-21 19:42:38 epoch:0 dataset: 2/17 step: 0/90 time:0.57+0.88 loss_avg:2.5133e-01
INFO: 2023-08-21 19:42:39 epoch:0 dataset: 2/17 step: 1/90 time:0.00+0.82 loss_avg:2.4228e-01
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 334, in <module>
    train(model, args)
  File "./train_1d.py", line 210, in train
    val_hicrep = evaluate(model, data_val_path, val_dataset, epoch, step)
  File "./train_1d.py", line 235, in evaluate
    get_predictions(val_save_path, data_val_path, 1534, patch_size) #assemble into one big matrix
  File "/home/dmitryp/dpinchuk/dmvfn/CVPR2023-DMVFN/scripts/assemble.py", line 5, in get_predictions
    if not os.path.exists(file_out):
NameError: name 'file_out' is not defined

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7ff434086240>
